name = "movies-main"
main = "server.js"
compatibility_date = "2024-10-01"

# Enable Node.js compatibility for Express.js and other Node modules
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm install"

# Environment variables that will be available to the Worker
[vars]
NODE_ENV = "production"

# Secrets that need to be set via `wrangler secret put`
# TMDB_API_KEY = "your_tmdb_api_key_here"  # Set this via: wrangler secret put TMDB_API_KEY
