name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TMDB_API: ${{ secrets.TMDB_API }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo environment variable (for testing only)
        run: |
          echo "TMDB_API is set (GitHub will mask the actual value)"
          echo "Using TMDB_API=$TMDB_API"

      - name: Use TMDB_API in a request
        run: |
          curl -H "Authorization: Bearer $TMDB_API" https://httpbin.org/bearer
