name: Build and Test

# Run workflow when pushing to main or when opening a PR
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    # Make secrets available to all steps in this job
    env:
      SERVICE_API: ${{ secrets.SERVICE_API }}
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Show environment variables (for testing only)
      - name: Echo environment variables
        run: |
          echo "SERVICE_API is set (but GitHub will mask the actual value)"
          echo "API_KEY is set (also masked in logs)"
          echo "Using SERVICE_API=$SERVICE_API"
          echo "Using API_KEY=$API_KEY"

      # Step 3: Example usage in a curl request
      - name: Use API key in a request
        run: |
          curl -H "Authorization: Bearer $SERVICE_API" https://httpbin.org/bearer
